"""empty message

Revision ID: 43cca267c00f
Revises: 
Create Date: 2021-06-02 09:27:50.833400

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = '43cca267c00f'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('company')
    op.drop_table('employees')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('employees',
    sa.Column('eid', sa.INTEGER(), server_default=sa.text("nextval('employees_eid_seq'::regclass)"), autoincrement=True, nullable=False),
    sa.Column('first_name', sa.VARCHAR(length=100), autoincrement=False, nullable=False),
    sa.Column('last_name', sa.VARCHAR(length=100), autoincrement=False, nullable=False),
    sa.Column('email_id', sa.VARCHAR(length=100), autoincrement=False, nullable=False),
    sa.Column('mobile_no', sa.VARCHAR(length=100), autoincrement=False, nullable=False),
    sa.Column('date_created', postgresql.TIMESTAMP(), autoincrement=False, nullable=True),
    sa.Column('date_modified', postgresql.TIMESTAMP(), autoincrement=False, nullable=True),
    sa.PrimaryKeyConstraint('eid', name='employees_pkey'),
    sa.UniqueConstraint('email_id', name='employees_email_id_key'),
    sa.UniqueConstraint('mobile_no', name='employees_mobile_no_key'),
    postgresql_ignore_search_path=False
    )
    op.create_table('company',
    sa.Column('cid', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('eid', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('company_name', sa.VARCHAR(length=100), autoincrement=False, nullable=False),
    sa.Column('branch', sa.VARCHAR(length=100), autoincrement=False, nullable=False),
    sa.Column('department', sa.VARCHAR(length=100), autoincrement=False, nullable=False),
    sa.Column('ceo', sa.VARCHAR(length=100), autoincrement=False, nullable=False),
    sa.Column('date_created', postgresql.TIMESTAMP(), autoincrement=False, nullable=True),
    sa.Column('date_modified', postgresql.TIMESTAMP(), autoincrement=False, nullable=True),
    sa.ForeignKeyConstraint(['eid'], ['employees.eid'], name='company_eid_fkey', ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('cid', name='company_pkey'),
    sa.UniqueConstraint('ceo', name='company_ceo_key')
    )
    # ### end Alembic commands ###
